### ISSUE TITLE
Investigate Reranking Algorithm to improve vector search results

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#48]
When retrieving data via ANN from Cassandra, a light-weight re-ranking for the purposes of determining what vector search results to pass the the LLM is necessary.

**Comment by karlunho-datastax** [comment]
I've been talking to Alejandro about what his team did at shopify. Simple things that can be done with re-ranking include looking at the articles that have lots of page views. Let's also take a look if there is some CQL query optimization opportunities as well.

**Comment by karlunho-datastax** [comment]
@xingh Take a look at Meta-Rank too - https://www.pinecone.io/learn/metarank/ We might just integrate with this product for now.

**Comment by xingh** [comment]
@karlunho-datastax 


# Updates on reranking re Cassio 

1. @hemidactylus last iteration essentially takes care of the first version of this. I added suggestions for how to manage this with columns, but this is good enough for rock and roll. 
2. When the llamaindex PR goes in with the data model refactor we can test these out of the box. 

Pinecone's hybrid search is pretty good. Investigating Metarank, this is what I found:

# Metarank 

## ML / Data Engineering

1. We would train it on some data to get it started. We can look at arxiv as a general data set. Featurization is done using configuration. 

```
 ltr-bm25-meta-minilm-ce:
    type: lambdamart
    backend:
      type: xgboost
      iterations: 100
    features:
      - query_title_minilm_ft
      - query_title_ce_ft
      - query_title_bm25
      - query_desc_bm25
      - query_bullets_bm25
      - category0
      - category1
      - category2
      - color
      - material
      - price
      - ratings
      - stars
      - template
      - weight
```
2. We can continue training it as new data set comes in. Arxiv has new data that comes in all the time. 

## Retrieval 
1. We can take whatever we are getting from CQL, Vector Search, Elastic/Lucene combination there of send it to Metarank and it will give us back better results, supposedly. 
2. Another approach which is only integrated with opensearch as a plugin is to use Metarank as the LTR (learning to rank) sub system. 
3. The advanced features as it relates to real-time user event based reranking is the cream. 


## Conclusion re Metarank
1. Its worth a try immediately without doing realtime training / realtime event based reranking via hardcoded metadata.
2. Next would be to feed metadata to an API that wraps metarank + cassio - would kick off a training job once a good amount of data is ingested, and then would be able to send reranked data. 


# Breadcrumbs/ Reference

- https://www.pinecone.io/learn/metarank/
- https://www.metarank.ai/
- https://demo.metarank.ai/
- https://github.com/metarank/metarank
- https://docs.metarank.ai/introduction/intro
- https://github.com/metarank/demo2
- https://docs.metarank.ai/reference/event-schema

- https://opensearch.org/blog/ltr-with-opensearch-and-metarank/
